// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD703kM-XoxRDvhg-B3-xCqJqQ-qjE96l4',
    appId: '1:753575401638:web:939aed17a644cefcea3c67',
    messagingSenderId: '753575401638',
    projectId: 'chatapp-2b64d',
    authDomain: 'chatapp-2b64d.firebaseapp.com',
    storageBucket: 'chatapp-2b64d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeR7fH29G3qPxiVYVQSlmLNpZDD6QKOw',
    appId: '1:753575401638:android:9839828314253913ea3c67',
    messagingSenderId: '753575401638',
    projectId: 'chatapp-2b64d',
    storageBucket: 'chatapp-2b64d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD3-44ncV_ifPrXYRiZGkl-UzXFOwQgsU',
    appId: '1:753575401638:ios:79985fd8c4cad16cea3c67',
    messagingSenderId: '753575401638',
    projectId: 'chatapp-2b64d',
    storageBucket: 'chatapp-2b64d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD3-44ncV_ifPrXYRiZGkl-UzXFOwQgsU',
    appId: '1:753575401638:ios:b523436881c29c1cea3c67',
    messagingSenderId: '753575401638',
    projectId: 'chatapp-2b64d',
    storageBucket: 'chatapp-2b64d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
